AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: API Gateway, with associated lambdas for the Contactz lambda.

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Parameters:
  VPCSecretName:
    Type: String
    Description: The name of the SecretsManager that has the vpc id
    Default: vpc-secret
  AuthSecretName:
    Type: String
    Description: The name of the SecretsManager that has the auth lambda ARN
    Default: auth-secret
  DbSecretName:
    Type: String
    Description: The name of the SecretsManager that has the database configuration
    Default: db-secret
  StageName:
    Type: String
    Default: prod
  ApiDomainName:
    Type: String
    Description: The api domain name
    Default: api.contactz.com.au
  AuthLambdaName:
    Type: String
    Description: The domain for the API ApiMapping
    Default: sam-authorizer
  JwtSecret:
    Type: String
    Description: The jwt secret required to create JWT tokens on registration/login
    Default: secret
Resources:
  AccessLogs:
    Type: AWS::Logs::LogGroup

  PublicApi:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      StageName:
        Ref: StageName
      Auth:
        AddDefaultAuthorizerToCorsPreflight: False # CORS: removes Authorizer from the automatically created OPTIONS methods
      DefinitionBody:
        Fn::Transform:
          Name: "AWS::Include"
          Parameters:
            Location: contact.openapi.yml
      AccessLogSetting:
        DestinationArn:
          Fn::GetAtt: AccessLogs.Arn
        Format: requestId:$context.requestId,method:$context.httpMethod,path:$context.path,SourceIp:$context.identity.sourceIp,xrayId:$context.xrayTraceId,principalId:$context.authorizer.principalId,RequestTime:$context.requestTime,AuthorizerLatency:$context.authorizer.integrationLatency,IntegrationLatency:$context.integrationLatency,ResponseLatency:$context.responseLatency,ResponseStatus:$context.status
      Tags:
        Name: API Gateway
        Description: API Gateway
  ContactFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role:
        Fn::GetAtt: ContactLambdaRole.Arn
      CodeUri: contact/code
      Handler: index.handler
      Runtime: nodejs12.x
      Description: CRUD functions for contact endpoints
      FunctionName: sam-contact-lambda
      Environment:
        Variables:
          DB_SECRET:
            Ref: DbSecretName
          JWT_SECRET:
            Ref: JwtSecret
      Tracing: Active
      Layers:
        - Ref: ContactDependenciesLayer
      VpcConfig:
        SecurityGroupIds:
          - Fn::Sub: "{{resolve:secretsmanager:${DbSecretName}:SecretString:sg}}"
        SubnetIds:
          - Fn::Sub: "{{resolve:secretsmanager:${VPCSecretName}:SecretString:subnet-private-apse2a}}"
          - Fn::Sub: "{{resolve:secretsmanager:${VPCSecretName}:SecretString:subnet-private-apse2b}}"
          - Fn::Sub: "{{resolve:secretsmanager:${VPCSecretName}:SecretString:subnet-private-apse2c}}"
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        Ping:
          Type: Api
          Properties:
            Path: /ping
            Method: get
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        UserRegister:
          Type: Api
          Properties:
            Path: /user/register
            Method: post
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        UserLogin:
          Type: Api
          Properties:
            Path: /user/login
            Method: post
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        UserLogout:
          Type: Api
          Properties:
            Path: /user/logout
            Method: post
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        UserRefreshToken:
          Type: Api
          Properties:
            Path: /user/refresh
            Method: post
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        ListTypes:
          Type: Api
          Properties:
            Path: /type
            Method: get
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        ListTypesFiltered:
          Type: Api
          Properties:
            Path: /type/{name}
            Method: get
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        ListContact:
          Type: Api
          Properties:
            Path: /contact
            Method: get
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        GetContact:
          Type: Api
          Properties:
            Path: /contact/{id}
            Method: get
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        CreateContact:
          Type: Api
          Properties:
            Path: /contact
            Method: post
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        UpdateContact:
          Type: Api
          Properties:
            Path: /contact/{id}
            Method: put
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        DeleteContact:
          Type: Api
          Properties:
            Path: /contact/{id}
            Method: delete
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        ListOrganisation:
          Type: Api
          Properties:
            Path: /org
            Method: get
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        GetOrganisation:
          Type: Api
          Properties:
            Path: /org/{id}
            Method: get
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        CreateOrganisation:
          Type: Api
          Properties:
            Path: /org
            Method: post
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        UpdateOrganisation:
          Type: Api
          Properties:
            Path: /org/{id}
            Method: put
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        DeleteOrganisation:
          Type: Api
          Properties:
            Path: /org/{id}
            Method: delete
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        ListAddress:
          Type: Api
          Properties:
            Path: /address
            Method: get
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        GetAddress:
          Type: Api
          Properties:
            Path: /address/{id}
            Method: get
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        CreateAddress:
          Type: Api
          Properties:
            Path: /address
            Method: post
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        UpdateAddress:
          Type: Api
          Properties:
            Path: /address/{id}
            Method: put
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        DeleteAddress:
          Type: Api
          Properties:
            Path: /address/{id}
            Method: delete
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        ListTag:
          Type: Api
          Properties:
            Path: /tag
            Method: get
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        GetTag:
          Type: Api
          Properties:
            Path: /tag/{id}
            Method: get
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        CreateTag:
          Type: Api
          Properties:
            Path: /tag
            Method: post
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        UpdateTag:
          Type: Api
          Properties:
            Path: /tag/{id}
            Method: put
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        DeleteTag:
          Type: Api
          Properties:
            Path: /tag/{id}
            Method: delete
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        ListGroup:
          Type: Api
          Properties:
            Path: /group
            Method: get
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        GetGroup:
          Type: Api
          Properties:
            Path: /group/{id}
            Method: get
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        CreateGroup:
          Type: Api
          Properties:
            Path: /group
            Method: post
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        UpdateGroup:
          Type: Api
          Properties:
            Path: /group/{id}
            Method: put
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName
        DeleteGroup:
          Type: Api
          Properties:
            Path: /group/{id}
            Method: delete
            RestApiId:
              Ref: PublicApi
            Stage:
              Ref: StageName

  ContactDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: contact-dependencies
      Description: All dependencies for contact lambda
      ContentUri: contact/dependencies/
      CompatibleRuntimes:
        - nodejs12.x
      RetentionPolicy: Delete

  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    DependsOn:
      - PublicApiStage # Needs the API to be set up, before mapping # https://github.com/awslabs/serverless-application-model/issues/192
    Properties:
      ApiId:
        Ref: PublicApi
      DomainName:
        Ref: ApiDomainName
      Stage:
        Ref: StageName
  #     ApiMappingKey: v1

  ContactLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Allows a lambda to access the KMS key to decrypt DB config data
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
      Policies:
        - PolicyName: "DecryptKMSAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "kms:Decrypt"
                  - "kms:DescribeKey"
                  - "kms:GenerateDataKey"
                Resource: "*"
        - PolicyName: "SecretManagerAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "secretsmanager:DescribeSecret"
                  - "secretsmanager:GetSecretValue"
                Resource: "*"
        - PolicyName: "XRayAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow" # xray permissions (required)
                Action:
                  - "xray:PutTraceSegments"
                  - "xray:PutTelemetryRecords"
                Resource:
                  - "*"
        - PolicyName: "CloudWatchAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:*"
                Resource:
                  - "*"

Outputs:
  PublicApiUrl:
    Description: URL of the API endpoint
    Value:
      Fn::Sub: "https://${PublicApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/"
  PublicApiId:
    Description: Api id of PublicApi
    Value:
      Ref: PublicApi
  ContactFunction:
    Description: "The contact lambda ARN"
    Value:
      Fn::GetAtt: ContactFunction.Arn
