(cd infra/network && sam build && sam deploy --profile contactz)
(cd infra/domain && sam build && sam deploy --profile contactz)
(cd infra/datastore && sam build && sam deploy --profile contactz)
(cd infra/authorizer/dependencies/nodejs && npm install)
(cd infra/authorizer && sam build && sam deploy --profile contactz)
(cd infra/network && sam build && sam deploy --profile contactz)
(cd api/config && sam build && sam deploy --profile contactz)
(cd api/public/contact/dependencies/nodejs && npm install)
(cd api/public && sam build && sam deploy --profile contactz)
