name: contactz build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Create S3 Bucket (sam-contactz)
        run: aws s3api head-bucket --bucket sam-contactz --region ap-southeast-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2
      - name: sam build (./infra/network)
        uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: "build"
        env:
          INPUT_DIRECTORY: ./infra/network
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2
      - name: sam deploy (./infra/network)
        uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: "deploy"
        env:
          INPUT_DIRECTORY: ./infra/network
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2
